version: "3.9"
services:

  cAdvisor-scraper:
    image: "chenbao0707/cadvisor-scraper"
    ports:
      - "8091:8080"
    networks:
      - nclbenchmarkNet

  benchmarkapp:
    image: "nclcloudcomputing/javabenchmarkapp"
    ports:
      - "8090:8080"
    networks:
      - nclbenchmarkNet

  mongo:
    image: mongo
    ports:
      - "8085:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - nclbenchmarkNet

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    networks:
      - nclbenchmarkNet

  cadvisor:
    image: "gcr.io/cadvisor/cadvisor:v0.43.0"
    ports:
      - "8082:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - nclbenchmarkNet

  locust:
    image: "locustio/locust"
    ports:
      - "8083:8089"
    volumes:
      - /E/newcastleUniversity/Modules/CloudComputing/assessment1:/mnt/locust
    command: -f /mnt/locust/locustfile.py
    networks:
      - nclbenchmarkNet

  visualizer:
    image: "dockersamples/visualizer"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8084:8080"
    networks:
      - nclbenchmarkNet



networks:
  nclbenchmarkNet:
