version: "3.9"
services:
  benchmarkapp:
    image: "nclcloudcomputing/javabenchmarkapp"
    deploy:
      replicas: 1
      resources:
        limits: # Container usage limits
          cpus: '0.5' # Hard limits CPU usage to 50%
          memory: 300M # Hard limits memory usage to 100M
        reservations:
          cpus: '0.25' # Keep 25% of CPU usage always available for the container
          memory: 175M # Reserve 75 MB of memory for the container
      placement:
        constraints: # Constraints to the placement of services
          - "node.role==manager" # Deploy only on manager nodes
          # - "node.labels.location==uk" Deploy to any node that contains the label key pair location==uk
          # - "node.hostname==docker-desktop" # Deploy to a specific hostname
    ports:
      - "8090:8080"
      # - ^Host | ^Container
    environment: # Environment variables. Such as $PATH
      ENV_KEY: ENV_VALUE
    networks:
      - nclbenchmarkNet

  mongo:
    image: mongo
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.role==manager"
    ports:
      - "8085:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - nclbenchmarkNet

  mongo-express:
    image: mongo-express
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.role==manager"
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    networks:
      - nclbenchmarkNet

  cadvisor:
    image: "gcr.io/cadvisor/cadvisor"
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.role==manager"
    ports:
      - "8082:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:rw
    networks:
      - nclbenchmarkNet

  locust:
    image: "locustio/locust"
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.role==manager"
    ports:
      - "8083:8089"
    volumes:
      - /E/newcastleUniversity/Modules/CloudComputing/assessment1:/mnt/locust
    command: -f /mnt/locust/locustfile.py
    networks:
      - nclbenchmarkNet

  visualizer:
    image: "dockersamples/visualizer"
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.role==manager"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8084:8080"
    networks:
      - nclbenchmarkNet


networks:
  nclbenchmarkNet:
